# ================================================================
# 📍 FILE: elysia/kernel/Cargo.toml
# ================================================================

[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
elysia_core = { path = "../elysia_core" }

# logging
log = "0.4"
env_logger = "0.11"

# async runtime
tokio = { version = "1", features = ["full"] }

# modules
marthe = { path = "../modules/marthe" }
portal = { path = "../modules/portal" }
